// Common Languages List
export const COMMON_LANGUAGES = [
  'Spanish',
  'Mandarin',
  'Cantonese',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Arabic',
  'Russian',
  'Japanese',
  'Korean',
  'Vietnamese',
  'Tagalog',
  'Polish',
  'Hindi',
  'Bengali',
  'Urdu',
  'Persian',
  'Turkish',
  'Greek',
  'Hebrew',
  'Thai',
  'Dutch',
  'Swedish',
  'Haitian Creole',
  'American Sign Language (ASL)',
  'Somali',
  'Punjabi',
  'Romanian',
  'Ukrainian',
  'Albanian',
  'Bosnian',
  'Serbian',
  'Croatian',
  'Swahili',
  'Amharic',
  'Tigrinya',
  'Nepali',
  'Burmese',
  'Khmer',
  'Laotian',
  'Farsi',
  'Pashto',
  'Dari'
].sort();

export const STANDARD_COLUMNS = {
  interpreterId: 'Interpreter ID (from client report)',
  interpreterName: 'Interpreter Name',
  minutes: 'Minutes Worked',
  hours: 'Hours Worked',
  date: 'Date/Period',
  languagePair: 'Language Pair',
  rate: 'Rate (from client report)'
};
